#=
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=#

fibonacci1 = 1
fibonacci2 = 2
res = 0
while fibonacci2 < 4 * 10^6
  if iseven(fibonacci2)
    res += fibonacci2
  end
  tmp = fibonacci1
  fibonacci1 = fibonacci2
  fibonacci2 = tmp + fibonacci2
end
println(sum)
